[[language]]
name = "c"
#indent = { tab-width = 8, unit = "        " }
indent = { tab-width = 8, unit = "\t" }
file-types = [ "c", "h"]
rulers = [99]
text-width = 99

[[language]]
name = "git-commit"
rulers = [72]
text-width = 72

[[language]]
name = "python"
rulers = [88]
text-width = 88